name: CI

on:
  push:
    branches: ["main"]
  pull_requests:
    branches: ["main"]

  # Manual run from Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - name: Build
        run: zig build test --summary all          
